version: "3.8"

services:
  commander:
    build:
      context: ./commander
    command: sh -c "while true; do sleep 1; done"
    volumes:
      - ./commander:/app/commander
      - .env:/app/.env
    env_file:
      - .env

  psql:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - cookbook:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - 5050:5050

volumes:
  cookbook:
